-- Template 112 task standar (urut per milestone)
insert into public.tasks (milestone_id, couple_id, title, note, sort_order)
-- Di-copy ke couple baru oleh server action (admin invite / register)

-- task seed template (dipakai aplikasi saat init couple baru)
create table if not exists public.task_templates (id uuid primary key default uuid_generate_v4(), milestone_slug text not null, title text not null, note text not null default '', sort_order int not null default 0);

insert into public.task_templates (milestone_slug, title, note, sort_order) values
('venue-akad', 'Tentukan tanggal akad & resepsi', '', 0),
('venue-akad', 'Survey 3–5 venue pilihan', '', 1),
('venue-akad', 'Booking venue & bayar DP', '', 2),
('venue-akad', 'Konfirmasi layout & dekorasi dengan venue', '', 3),
('venue-akad', 'Gladi resik di venue', '', 4),
('venue-akad', 'Cek ulang venue H-3', '', 5),
('vendor-utama', 'Booking fotografer & videografer', '', 0),
('vendor-utama', 'Survey & booking katering', '', 1),
('vendor-utama', 'Booking dekorasi & florist', '', 2),
('vendor-utama', 'Booking MC pernikahan', '', 3),
('vendor-utama', 'Booking hiburan / live music', '', 4),
('vendor-utama', 'Booking kendaraan pengantin', '', 5),
('vendor-utama', 'Konfirmasi jadwal semua vendor H-1 bulan', '', 6),
('vendor-utama', 'Briefing vendor H-1 hari', '', 7),
('busana-penampilan', 'Tentukan konsep busana pengantin', '', 0),
('busana-penampilan', 'Survey & booking wedding organizer busana / MUA', '', 1),
('busana-penampilan', 'Booking baju pengantin & fitting pertama', '', 2),
('busana-penampilan', 'Fitting kedua & revisi', '', 3),
('busana-penampilan', 'Final fitting & ambil baju', '', 4),
('busana-penampilan', 'Persiapkan busana keluarga inti', '', 5),
('busana-penampilan', 'Trial make up & hairdo', '', 6),
('undangan-tamu', 'Buat daftar tamu awal', '', 0),
('undangan-tamu', 'Finalisasi jumlah tamu', '', 1),
('undangan-tamu', 'Desain undangan (fisik & digital)', '', 2),
('undangan-tamu', 'Cetak undangan fisik', '', 3),
('undangan-tamu', 'Kirim undangan gelombang 1 (tamu jauh)', '', 4),
('undangan-tamu', 'Kirim undangan gelombang 2 (tamu lokal)', '', 5),
('undangan-tamu', 'Konfirmasi RSVP & update daftar hadir', '', 6),
('undangan-tamu', 'Siapkan souvenir & amplop', '', 7),
('undangan-tamu', 'Booking penginapan untuk tamu jauh', '', 8),
('konsep-dekorasi', 'Tentukan tema & konsep pernikahan', '', 0),
('konsep-dekorasi', 'Tentukan palet warna utama', '', 1),
('konsep-dekorasi', 'Diskusi konsep dekorasi dengan vendor', '', 2),
('konsep-dekorasi', 'Konfirmasi dekorasi pelaminan & meja tamu', '', 3),
('konsep-dekorasi', 'Siapkan wedding props & detail dekorasi', '', 4),
('konsep-dekorasi', 'Cek hasil dekorasi venue di hari pemasangan', '', 5),
('anggaran-administrasi', 'Buat anggaran awal & alokasi per kategori', '', 0),
('anggaran-administrasi', 'Buat spreadsheet perbandingan vendor', '', 1),
('anggaran-administrasi', 'Catat semua DP & jadwal pelunasan vendor', '', 2),
('anggaran-administrasi', 'Buat rundown acara detail', '', 3),
('anggaran-administrasi', 'Briefing keluarga & pagar ayu/bagus', '', 4),
('anggaran-administrasi', 'Siapkan dana cash untuk kebutuhan hari-H', '', 5),
('dokumen-kua', 'N1 – Surat Pengantar Nikah dari RT/RW', '', 0),
('dokumen-kua', 'N2 – Akta Kelahiran (asli + 3 fotokopi)', '', 1),
('dokumen-kua', 'N4 – Surat Keterangan Asal-Usul dari Kelurahan', '', 2),
('dokumen-kua', 'KTP asli & fotokopi (3 lembar)', '', 3),
('dokumen-kua', 'Fotokopi KTP wali nikah (3 lembar)', '', 4),
('dokumen-kua', 'KK asli & fotokopi (3 lembar)', '', 5),
('dokumen-kua', 'Pas foto 2×3 – 5 lembar (latar biru/merah)', '', 6),
('dokumen-kua', 'Pas foto 3×4 – 5 lembar (latar biru/merah)', '', 7),
('dokumen-kua', 'Surat pernyataan belum menikah (bermaterai)', '', 8),
('dokumen-kua', 'Konsultasi & daftar ke KUA setempat', '', 9),
('dokumen-kua', 'Surat izin orang tua / N5 (jika usia < 21 tahun)', '', 10),
('dokumen-kua', 'Akta cerai / surat kematian pasangan sebelumnya', '', 11),
('mahar', 'Diskusi mahar dengan pasangan & keluarga', '', 0),
('mahar', 'Tentukan mahar & bentuknya', '', 1),
('mahar', 'Siapkan mahar H-3', '', 2),
('hari-h', 'Bangun pagi & sarapan bergizi', '', 0),
('hari-h', 'Mulai make up & hairdo sesuai jadwal', '', 1),
('hari-h', 'Briefing terakhir dengan semua vendor & keluarga', '', 2),
('hari-h', 'Cek dekorasi & sound system venue', '', 3),
('hari-h', 'Prosesi akad nikah', '', 4),
('hari-h', 'Sesi foto keluarga & pengantin', '', 5),
('hari-h', 'Resepsi & sambut tamu', '', 6),
('hari-h', 'Periksa barang bawaan sebelum pulang', '', 7),
('hari-h', 'Istirahat & nikmati momen bersama pasangan', '', 8),
('seserahan', 'Perlengkapan Ibadah - Mukena', '', 0),
('seserahan', 'Perlengkapan Ibadah - Sejadah', '', 1),
('seserahan', 'Perlengkapan Ibadah - Tasbih', '', 2),
('seserahan', 'Perlengkapan Ibadah - Sarung', '', 3),
('seserahan', 'Perlengkapan Ibadah - Al-Qur''an', '', 4),
('seserahan', 'Pakaian - Kerudung', '', 5),
('seserahan', 'Pakaian - Blousse', '', 6),
('seserahan', 'Pakaian - Outer', '', 7),
('seserahan', 'Pakaian - Piyama', '', 8),
('seserahan', 'Pakaian - Pants', '', 9),
('seserahan', 'Skin Care - Facial Wash', '', 10),
('seserahan', 'Skin Care - Mosturaizer', '', 11),
('seserahan', 'Skin Care - Serum', '', 12),
('seserahan', 'Skin Care - Toner', '', 13),
('seserahan', 'Skin Care - Sunscreen', '', 14),
('seserahan', 'Skin Care - Sleep Mask', '', 15),
('seserahan', 'Skin Care - Cleansing', '', 16),
('seserahan', 'Make Up - Eyeliner', '', 17),
('seserahan', 'Make Up - Eyeshadow', '', 18),
('seserahan', 'Make Up - Maskara', '', 19),
('seserahan', 'Make Up - Powder', '', 20),
('seserahan', 'Make Up - Lipstick', '', 21),
('seserahan', 'Make Up - Lipbalm', '', 22),
('seserahan', 'Make Up - Blush On', '', 23),
('seserahan', 'Body Care - Body Wash', '', 24),
('seserahan', 'Body Care - Body Scrub', '', 25),
('seserahan', 'Body Care - Deodoran', '', 26),
('seserahan', 'Body Care - Parfum', '', 27),
('seserahan', 'Toiletries - Handuk', '', 28),
('seserahan', 'Toiletries - Sampo', '', 29),
('seserahan', 'Toiletries - Pasta Gigi', '', 30),
('seserahan', 'Toiletries - Sikat Gigi', '', 31),
('seserahan', 'Toiletries - Toner Rambut', '', 32),
('seserahan', 'Pakaian Dalam - CD', '', 33),
('seserahan', 'Pakaian Dalam - Bra', '', 34),
('seserahan', 'Pakaian Dalam - Lingerie', '', 35),
('seserahan', 'Pakaian Dalam - Tanktop', '', 36),
('seserahan', 'Aksesoris - Tas', '', 37),
('seserahan', 'Aksesoris - Sepatu', '', 38),
('seserahan', 'Aksesoris - Sendal', '', 39),
('seserahan', 'Aksesoris - Jam Tangan', '', 40),
('seserahan', 'Aksesoris - Dompet', '', 41),
('seserahan', 'Perhiasan - Cincin', '', 42),
('seserahan', 'Perhiasan - Gelang', '', 43),
('seserahan', 'Perhiasan - Kalung', '', 44),
('seserahan', 'Perhiasan - Anting', '', 45);

-- RLS: template bisa dibaca semua user terauth, diedit admin saja
alter table public.task_templates enable row level security;
create policy "template read" on public.task_templates for select using (auth.role() = 'authenticated');
create policy "template admin" on public.task_templates for all
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role='admin'));